title: "Field Data Collection"
description: "Discover the right tool for your data collection needs. This workshop introduces Field Maps, QuickCapture, Survey123, and QField, covering key features, common workflows, and practical applications for gathering and managing field data efficiently."
github_repo_url: "https://github.com/TrentU-MaDGIC/FieldDataCollection/"

# Use remote theme
remote_theme: just-the-docs/just-the-docs

color_scheme: light
search_enabled: true

# Required for remote themes
plugins:
  - jekyll-remote-theme

# Build settings
url: "https://TrentU-MaDGIC.github.io"
baseurl: "/FieldDataCollection"
